import { EventCard } from "@/components/EventCard";
import { Event } from "@/types/Event";
import Head from "next/head";
import { useEffect, useState } from "react";
import { CardsGrid, HomeContainer, HomeTitle } from "./styles";

export default function Home() {
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchEvents = async () => {
      try {
        const response = await fetch('http://localhost:8000/api/events_list');
        if (!response.ok) {
          throw new Error('Erro ao buscar eventos');
        }
        const data = await response.json();
        if (data.success && data.events && Array.isArray(data.events.data)) {
          setEvents(data.events.data); 
        } else {
          throw new Error('Formato de resposta inesperado');
        }
      } catch (error) {
        setError(error.message);
      } finally {
        setLoading(false);
      }
    };

    fetchEvents();
  }, []);

  if (loading) return <p>Carregando eventos...</p>;
  if (error) return <p>Erro: {error}</p>;

  return (
    <>
      <Head>
        <title>Morena eventos.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomeContainer>
        <div>
          <HomeTitle>Eventos da morena</HomeTitle>
          <CardsGrid>
            {events.map(event => (
              <EventCard key={event.id} event={event} />
            ))}
          </CardsGrid>
        </div>
      </HomeContainer>
    </>
  );
}
