import Head from "next/head";



export default function Home() {
  return (
    <>
      <Head>
        <title>Morena eventos.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h2>Hello world!</h2>
      </main>
    </>
  );
}
